### ISSUE TITLE
Overleaf textarea on Firefox

### ISSUE THREAD

**Issue by hadikhzouz** [abhijithvijayan/web-extension-starter#83]
First of all, thank you so much for this great tool. 
I have, however, experienced the following bugs:

1- Overleaf textarea, cannot recognize the language used in overleaf, for example, when writing [In \cite{xyz}, the Authors .....], overleaf textarea recognizes the following [In , the Authors ....] which prevent Grammarly from working properly. 
2- In order to regenerate a pdf file on overleaf, you cannot just simply disable the extension of the overleaf textarea, but you have to deactivate it completely from the settings.

I really hope that you can solve these two problems.
Looking forward to hearing back from you. 
Thank you in advance.

**Comment by abhijith-vijayan** [comment]
What?

**Comment by abhijithvijayan** [comment]
What?---- On Sat, 22 Jan 2022 16:27:14 +0530  ***@***.******@***.***> wrote ---- 
First of all, thank you so much for this great tool. 
I have, however, experienced the following bugs: 
1- Overleaf textarea, cannot recognize the language used in overleaf, for example, when writing [In cite{xyz}, the Authors .....], overleaf textarea recognizes the following [In , the Authors ....] which prevent Grammarly from working properly. 
2- In order to regenerate a pdf file on overleaf, you cannot just simply disable the extension of the overleaf textarea, but you have to deactivate it completely from the settings. 
I really hope that you can solve these two problems. 
Looking forward to hearing back from you. 
Thank you in advance.

**Comment by hadikhzouz** [comment]
Here are some screenshots for what I meant in point 1:


[image: grafik.png]
[image: grafik.png]

Point 2 is less important for me.

**Comment by abhijithvijayan** [comment]
@hadikhzouz there is no image attached here. and also overleaf or any extension that is intended to work with overleaf has no relation with this project. Please submit the issue to the right repository of the extension that you are using.
